# Generated by Django 4.0 on 2022-05-13 13:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='books'),
        ),
    ]
