# Generated by Django 4.0 on 2022-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookURL',
            field=models.URLField(null=True),
        ),
    ]
